CREATE TABLE ARTIST(
        ID BIGINT  PRIMARY KEY AUTO_INCREMENT,
        FIRST_NAME VARCHAR(255),
        LAST_NAME VARCHAR(255),
        ARTIST_NAME VARCHAR(255),
        DATE_OF_BIRTH NOT NULL,
        GENRE VARCHAR(255)
        );